# Site settings
name:  Vinsen Blog
email: vinsen_zhang@163.com
author: Freud Kang
url: "https://github.com/VinsenZhang"
github: https://github.com/VinsenZhang
baseurl: "/blog"
description: Actually, less is more!
meta_description: 个人博客;学而不思则罔;思而不学则殆;生命不止;折腾不休
motto: It's our wits that make us men.
banner: 学而不思则罔，思而不学则殆。

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: VinsenZhang
highlighter: Pygments

# Build settings
markdown: kramdown

